sites_path: "../data/processed/Sites.csv"
isotopes_path: "../data/processed/isotopes/isotopes_data.csv"
climate_path: "../data/processed/climate"

plot_font:
  size: "16"
  family: "Times New Roman"

save_path: "../results/Paper_003"

site_to_order:
  ALA: 1
  MZ: 2
  CAN: 3
  GUT: 4
  FOR: 5
  TOR: 6
  LAN: 7
  INA: 8
  ILO: 9
  KOL: 10
  TAY: 11
  PYAD: 12
  YAK: 13
  IND: 14
  TUR: 15
  ENE: 16
  KHAK: 17
  IRK: 18
  OLH: 19
  DAV: 20
  AL: 21
  ALT: 22
  HO: 23
  CH: 24

site_to_color:
  CAN: blue
  MZ: blue
  ALA: blue
  IND: blue
  YAK: blue
  PYAD: blue
  TAY: blue
  KOL: blue
  FOR: blue
  LAN: blue
  TOR: blue
  INA: blue
  GUT: blue
  ILO: blue
  ENE: green
  TUR: blue
  KHAK: green
  DAV: green
  OLH: green
  IRK: green
  ALT: red
  AL: red
  HO: red
  CH: red

isotopes:
  - 2H
  - 13C
  - 18O

isotope_to_name:
  2H: "$\u03B4^{2}$H"
  13C: "$\u03B4^{13}$C"
  18O: "$\u03B4^{18}$O"
  
isotope_to_color:
  2H: "#2DFAA5"
  13C: "#E3D41E"
  18O: "#FA5D2A"

isotope_to_title:
  2H: "$\u03B4^{2}H$, $\u2030$"
  13C: "$\u03B4^{13}C$, $\u2030$"
  18O: "$\u03B4^{18}O$, $\u2030$"

sites_trends:
  - CAN
  - GUT
  - INA
  - ILO
  - TAY
  - IND

clim_indexes:
  - "Temperature"
  - "Precipitation"
  - "VPD"
  - "Relative Humidity"
  - "Sunshine Duration"

clim_index_to_name:
  Temp: "Temperature"
  Prec: "Precipitation"
  SD: "Sunshine Duration"
  VPD: "VPD"
  RH: "Relative Humidity"

zscore_trends_kwargs:
  xlim: 
    - 1900
    - 2000
  ylim:
    - -2.5
    - 2.5
  yticks:
    - -1.5
    - 0.0
    - 1.5

heatmap_kwargs:
  start_year: 1960
  end_year: 2000
  min_p_value: 0.05
